### ISSUE TITLE
fakeroot-tcp for Arm architecture

### ISSUE THREAD

**Issue by azinsharaf** [yuk7/arch-prebuilt#1]
hi @yuk7 ,
I've followed your `wsldl` package and installed Arch on WSL1 (on Arm architecture). The OS works fine, i just can't install `yay` because i can't find `fakeroot-tcp` for Arm. Do you have any advice?

**Comment by yuk7** [comment]
I think you can try fakeroot-tcp which is on the AUR.
https://aur.archlinux.org/packages/fakeroot-tcp

If you cannot prepare a build environment, you can use these prebuilt pkgs:
* https://mirrors.cloud.tencent.com/arch4edu/aarch64/fakeroot-tcp-1.32.1-1-aarch64.pkg.tar.zst
* https://arch4edu.mirror.kescher.at/aarch64/fakeroot-tcp-1.32.1-1-aarch64.pkg.tar.zst

```bash
sudo pacman -U fakeroot-tcp-1.32.1-1-aarch64.pkg.tar.zst

```

**Comment by azinsharaf** [comment]
wow it worked! I couldn't install it from the `AUR` link but the `tar.zst` file from the `mirror` worked. Thanks a lot!
